//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.15 at 09:22:26 AM VET 
//


package com.ula.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.statemachine.org/state_machine.xsd}source"/>
 *         &lt;element ref="{http://www.statemachine.org/state_machine.xsd}target"/>
 *         &lt;element ref="{http://www.statemachine.org/state_machine.xsd}eventArc"/>
 *         &lt;element ref="{http://www.statemachine.org/state_machine.xsd}bendPoints" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "target",
    "eventArc",
    "bendPoints"
})
@XmlRootElement(name = "Arc")
public class Arc {

    @XmlElement(required = true)
    protected Source source;
    @XmlElement(required = true)
    protected Target target;
    @XmlElement(required = true)
    protected EventArc eventArc;
    @XmlElement(required = true)
    protected List<BendPoints> bendPoints;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link Target }
     *     
     */
    public Target getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link Target }
     *     
     */
    public void setTarget(Target value) {
        this.target = value;
    }

    /**
     * Gets the value of the eventArc property.
     * 
     * @return
     *     possible object is
     *     {@link EventArc }
     *     
     */
    public EventArc getEventArc() {
        return eventArc;
    }

    /**
     * Sets the value of the eventArc property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventArc }
     *     
     */
    public void setEventArc(EventArc value) {
        this.eventArc = value;
    }

    /**
     * Gets the value of the bendPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bendPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBendPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BendPoints }
     * 
     * 
     */
    public List<BendPoints> getBendPoints() {
        if (bendPoints == null) {
            bendPoints = new ArrayList<BendPoints>();
        }
        return this.bendPoints;
    }

}
